[build]
  publish = "."
  command = ""

# SPA fallback (serve index.html for all routes)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Never cache the service worker
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Service-Worker-Allowed = "/"

# Don't cache the manifest either (lets icons/fields update)
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

# (Optional) extra safety/default header
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
